-- DO NOT EDIT THIS FILE DIRECTLY
-- This is a file generated from a literate programing source file located at
-- https://github.com/rossputin/dot-hammerspoon/blob/master/init.org.
-- You should make any changes there and regenerate it from Emacs org-mode using C-c C-v t

hyper       = {"cmd","alt","ctrl"}
cmd_ctrl    = {"cmd","ctrl"}

hs.hotkey.bind(hyper, "H", function()
    hs.alert.show("Hammerspoon config! Alt+F = Finder, Alt+E = Emacs, Alt+T = iTerm")
end)
